// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACard: typeof import('ant-design-vue/es')['Card'];
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid'];
    ADivider: typeof import('ant-design-vue/es')['Divider'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    Header: typeof import('./../src/components/Header/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
  }
}
