export default [
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2001',
    total_online: '338',
    total_offline: '1571',
    permanent_online: '218',
    permanent_offline: '998',
    long_online: '77',
    long_offline: '372',
    short_online: '43',
    short_offline: '201',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '肇庆市XXX股份有限公司',
    yearNo: '2002',
    total_online: '1001',
    total_offline: '5901',
    permanent_online: '397',
    permanent_offline: '2867',
    long_online: '390',
    long_offline: '2196',
    short_online: '214',
    short_offline: '838',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '韶关市XXX股份有限公司',
    yearNo: '2003',
    total_online: '2665',
    total_offline: '12009',
    permanent_online: '491',
    permanent_offline: '3086',
    long_online: '1327',
    long_offline: '6024',
    short_online: '847',
    short_offline: '2899',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '茂名市XXX股份有限公司',
    yearNo: '2004',
    total_online: '2480',
    total_offline: '13546',
    permanent_online: '698',
    permanent_offline: '4707',
    long_online: '842',
    long_offline: '4634',
    short_online: '940',
    short_offline: '4205',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '清远市XXX股份有限公司',
    yearNo: '2005',
    total_online: '1843',
    total_offline: '11125',
    permanent_online: '532',
    permanent_offline: '4094',
    long_online: '569',
    long_offline: '3522',
    short_online: '742',
    short_offline: '3509',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2006',
    total_online: '1964',
    total_offline: '11132',
    permanent_online: '355',
    permanent_offline: '2104',
    long_online: '559',
    long_offline: '3373',
    short_online: '1050',
    short_offline: '5655',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2007',
    total_online: '2159',
    total_offline: '11856',
    permanent_online: '285',
    permanent_offline: '1870',
    long_online: '597',
    long_offline: '3316',
    short_online: '1277',
    short_offline: '6670',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2008',
    total_online: '2554',
    total_offline: '36739',
    permanent_online: '387',
    permanent_offline: '3339',
    long_online: '692',
    long_offline: '25715',
    short_online: '1475',
    short_offline: '7685',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2009',
    total_online: '3087',
    total_offline: '22883',
    permanent_online: '418',
    permanent_offline: '4492',
    long_online: '815',
    long_offline: '6270',
    short_online: '1854',
    short_offline: '12121',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2010',
    total_online: '2991',
    total_offline: '21901',
    permanent_online: '596',
    permanent_offline: '6190',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '651',
    thirty_offline: '5965',
    decade_online: '1744',
    decade_offline: '9746',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2011',
    total_online: '5053',
    total_offline: '36522',
    permanent_online: '1387',
    permanent_offline: '13980',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '936',
    thirty_offline: '7904',
    decade_online: '2730',
    decade_offline: '14638',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2012',
    total_online: '4387',
    total_offline: '46384',
    permanent_online: '1011',
    permanent_offline: '13870',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '795',
    thirty_offline: '8874',
    decade_online: '2581',
    decade_offline: '23640',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2013',
    total_online: '4274',
    total_offline: '50657',
    permanent_online: '816',
    permanent_offline: '13032',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '904',
    thirty_offline: '11463',
    decade_online: '2554',
    decade_offline: '26162',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2014',
    total_online: '3911',
    total_offline: '53550',
    permanent_online: '790',
    permanent_offline: '14895',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '701',
    thirty_offline: '9181',
    decade_online: '2420',
    decade_offline: '29474',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2015',
    total_online: '5207',
    total_offline: '72412',
    permanent_online: '1199',
    permanent_offline: '17340',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '1016',
    thirty_offline: '15594',
    decade_online: '2992',
    decade_offline: '39478',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2016',
    total_online: '5958',
    total_offline: '90291',
    permanent_online: '1461',
    permanent_offline: '26334',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '1465',
    thirty_offline: '24551',
    decade_online: '3032',
    decade_offline: '39406',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '揭阳市XXX股份有限公司',
    yearNo: '2017',
    total_online: '6145',
    total_offline: '100796',
    permanent_online: '1719',
    permanent_offline: '34394',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '1444',
    thirty_offline: '25954',
    decade_online: '2982',
    decade_offline: '40448',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '湛江市XXX股份有限公司',
    yearNo: '2018',
    total_online: '6537',
    total_offline: '102554',
    permanent_online: '1604',
    permanent_offline: '30081',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '1209',
    thirty_offline: '22271',
    decade_online: '3724',
    decade_offline: '50202',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '中山市XXX股份有限公司',
    yearNo: '2019',
    total_online: '5206',
    total_offline: '97659',
    permanent_online: '1435',
    permanent_offline: '33963',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '970',
    thirty_offline: '20512',
    decade_online: '2801',
    decade_offline: '43184',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '梅州市XXX股份有限公司',
    yearNo: '2020',
    total_online: '10012',
    total_offline: '200051',
    permanent_online: '4262',
    permanent_offline: '81231',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '2209',
    thirty_offline: '63063',
    decade_online: '3541',
    decade_offline: '55757',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2021',
    total_online: '5518',
    total_offline: '107206',
    permanent_online: '1330',
    permanent_offline: '37382',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '1677',
    thirty_offline: '34029',
    decade_online: '2511',
    decade_offline: '35795',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '佛山市XXX股份有限公司',
    yearNo: '2022',
    total_online: '1',
    total_offline: '0',
    permanent_online: '1',
    permanent_offline: '0',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '东莞市XXX股份有限公司',
    yearNo: '2022',
    total_online: '11',
    total_offline: '0',
    permanent_online: '11',
    permanent_offline: '0',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
  {
    company: '广州市XXX股份有限公司',
    yearNo: '2052',
    total_online: '19',
    total_offline: '174',
    permanent_online: '19',
    permanent_offline: '174',
    long_online: '0',
    long_offline: '0',
    short_online: '0',
    short_offline: '0',
    thirty_online: '0',
    thirty_offline: '0',
    decade_online: '0',
    decade_offline: '0',
    five_online: '0',
    five_offline: '0',
  },
];
